// nextjs-admin/src/app/(dashboard)/ai-worker/page.tsx
"use client";

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type KeyboardEvent,
} from "react";
import {
  BarChart3,
  Bot,
  CheckCircle2,
  ChevronLeft,
  Clock,
  FileBox,
  FileText,
  Loader2,
  MessageSquare,
  Plus,
  RefreshCw,
  Send,
  Sparkles,
  Trash2,
  TrendingUp,
  Users,
  Wallet,
} from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import {
  deleteAiConversation,
  deleteAiReport,
  fetchAiConversation,
  fetchAiConversations,
  fetchAiReports,
  formatChatTime,
  formatFileSize,
  formatSidebarDate,
  type AiChatMessage,
  type AiConversationListItem,
  type AiReport,
} from "@/lib/firestore/aiAssistant";
import { sendAiMessage } from "@/lib/api/aiActions";
import { formatAiMessage } from "@/lib/aiMarkdown";

type LocalMessage = {
  id: string;
  role: "user" | "assistant";
  content: string;
  time: string;
  model?: string;
};

type SidebarTab = "conversations" | "reports";

const WELCOME_TEXT =
  "Сайн байна уу! Би таны **AI бизнес туслах ажилтан**. GrammGold-ын бүх бизнес мэдээлэлд хандах боломжтой.\n\n🔍 **Миний чадварууд:**\n• Бизнесийн тайлан гаргах (PDF, Word)\n• Борлуулалт, хэрэглэгчийн шинжилгээ\n• KPI тооцоолол, MoM өсөлт\n• Хэрэглэгчийн дэлгэрэнгүй мэдээлэл хайх\n• Стратегийн зөвлөгөө өгөх\n\nДоорх товчлууруудаас сонгох эсвэл өөрийн асуултаа бичнэ үү! 👇";

const QUICK_PROMPTS: { icon: React.ReactNode; label: string; prompt: string }[] = [
  {
    icon: <BarChart3 className="h-3.5 w-3.5" />,
    label: "Өнөөдрийн тайлан",
    prompt: "Өнөөдрийн бизнесийн товч тайлан гаргаж өгнө үү.",
  },
  {
    icon: <TrendingUp className="h-3.5 w-3.5" />,
    label: "Сарын шинжилгээ",
    prompt:
      "Энэ сарын борлуулалтын шинжилгээ хийж, өмнөх сартай харьцуулна уу.",
  },
  {
    icon: <Users className="h-3.5 w-3.5" />,
    label: "Топ хэрэглэгчид",
    prompt:
      "Хамгийн их алт эзэмшдэг топ 20 хэрэглэгчийн Pareto шинжилгээ хийнэ үү.",
  },
  {
    icon: <FileText className="h-3.5 w-3.5" />,
    label: "PDF тайлан",
    prompt: "Энэ сарын бизнесийн гүйцэтгэлийн дэлгэрэнгүй PDF тайлан үүсгэнэ үү.",
  },
  {
    icon: <Wallet className="h-3.5 w-3.5" />,
    label: "Мөнгөн зарлага",
    prompt:
      "Хүлээгдэж буй зарлагын хүсэлтүүдийг шинжилж, эрсдэлийн үнэлгээ хийнэ үү.",
  },
  {
    icon: <FileBox className="h-3.5 w-3.5" />,
    label: "KPI Dashboard",
    prompt:
      "Бидний гол KPI үзүүлэлтүүдийг (DAU, ARPU, Retention, Conversion) тооцоолж, хүснэгтээр харуулна уу.",
  },
];

function newId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function currentHHMM(): string {
  const d = new Date();
  return `${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
}

function welcomeMessage(): LocalMessage {
  return {
    id: newId(),
    role: "assistant",
    content: WELCOME_TEXT,
    time: currentHHMM(),
  };
}

export default function AiWorkerPage() {
  const [messages, setMessages] = useState<LocalMessage[]>([welcomeMessage()]);
  const [input, setInput] = useState("");
  const [sending, setSending] = useState(false);
  const [conversationId, setConversationId] = useState<string | null>(null);

  const [conversations, setConversations] = useState<AiConversationListItem[]>(
    []
  );
  const [reports, setReports] = useState<AiReport[]>([]);
  const [loadingConversations, setLoadingConversations] = useState(false);
  const [loadingReports, setLoadingReports] = useState(false);

  const [showSidebar, setShowSidebar] = useState(true);
  const [activeTab, setActiveTab] = useState<SidebarTab>("conversations");

  const [confirmDeleteConv, setConfirmDeleteConv] = useState<AiConversationListItem | null>(null);
  const [confirmDeleteReport, setConfirmDeleteReport] = useState<AiReport | null>(null);

  const scrollRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom on message changes
  useEffect(() => {
    scrollRef.current?.scrollTo({
      top: scrollRef.current.scrollHeight,
      behavior: "smooth",
    });
  }, [messages, sending]);

  const loadConversations = useCallback(async () => {
    setLoadingConversations(true);
    try {
      const list = await fetchAiConversations();
      setConversations(list);
    } catch (err) {
      console.error("Failed to load conversations", err);
    } finally {
      setLoadingConversations(false);
    }
  }, []);

  const loadReports = useCallback(async () => {
    setLoadingReports(true);
    try {
      const list = await fetchAiReports();
      setReports(list);
    } catch (err) {
      console.error("Failed to load reports", err);
    } finally {
      setLoadingReports(false);
    }
  }, []);

  useEffect(() => {
    void loadConversations();
    void loadReports();
  }, [loadConversations, loadReports]);

  const send = useCallback(
    async (text: string) => {
      const trimmed = text.trim();
      if (!trimmed || sending) return;

      const userMsg: LocalMessage = {
        id: newId(),
        role: "user",
        content: trimmed,
        time: currentHHMM(),
      };
      setMessages((m) => [...m, userMsg]);
      setInput("");
      setSending(true);

      try {
        const result = await sendAiMessage({
          message: trimmed,
          conversationId,
        });
        setConversationId(result.conversationId || null);
        setMessages((m) => [
          ...m,
          {
            id: newId(),
            role: "assistant",
            content: result.message,
            time: currentHHMM(),
            model: result.model,
          },
        ]);
        void loadConversations();
        // If response mentions a report, refresh reports list
        if (
          result.message &&
          (result.message.includes("storage.googleapis.com") ||
            result.message.toLowerCase().includes("report"))
        ) {
          void loadReports();
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : "Алдаа гарлаа.";
        setMessages((m) => [
          ...m,
          {
            id: newId(),
            role: "assistant",
            content: `❌ Уучлаарай, алдаа гарлаа. Дахин оролдоно уу.\n\n\`${msg}\``,
            time: currentHHMM(),
          },
        ]);
      } finally {
        setSending(false);
      }
    },
    [sending, conversationId, loadConversations, loadReports]
  );

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      void send(input);
    }
  };

  const handleNewConversation = () => {
    setConversationId(null);
    setMessages([
      {
        id: newId(),
        role: "assistant",
        content: "🆕 Шинэ яриа эхэлж байна. Танд юугаар туслах вэ?",
        time: currentHHMM(),
      },
    ]);
    setInput("");
  };

  const handleLoadConversation = async (conv: AiConversationListItem) => {
    try {
      const detail = await fetchAiConversation(conv.id);
      setConversationId(detail.id);
      setMessages(
        detail.messages.map<LocalMessage>((m: AiChatMessage) => ({
          id: newId(),
          role: m.role,
          content: m.content,
          time: formatChatTime(m.timestamp),
        }))
      );
    } catch (err) {
      console.error("Failed to load conversation", err);
      toast.error("Яриа татаж чадсангүй.");
    }
  };

  const handleConfirmDeleteConv = async () => {
    const conv = confirmDeleteConv;
    if (!conv) return;
    try {
      await deleteAiConversation(conv.id);
      if (conversationId === conv.id) handleNewConversation();
      toast.success("Яриа устгагдлаа.");
      void loadConversations();
    } catch (err) {
      console.error("Failed to delete conversation", err);
      toast.error("Устгахад алдаа гарлаа.");
    } finally {
      setConfirmDeleteConv(null);
    }
  };

  const handleConfirmDeleteReport = async () => {
    const r = confirmDeleteReport;
    if (!r) return;
    try {
      await deleteAiReport(r.id);
      toast.success("Тайлан устгагдлаа.");
      void loadReports();
    } catch (err) {
      console.error("Failed to delete report", err);
      toast.error("Устгахад алдаа гарлаа.");
    } finally {
      setConfirmDeleteReport(null);
    }
  };

  const showQuickPrompts = useMemo(
    () => messages.length <= 1 && !sending,
    [messages.length, sending]
  );

  return (
    <div className="-mx-1 flex h-[calc(100vh-7rem)] gap-3">
      {/* Sidebar */}
      {showSidebar && (
        <aside className="hidden w-72 shrink-0 flex-col overflow-hidden rounded-xl border border-border-light bg-card lg:flex">
          <div className="flex border-b border-border-light">
            <SidebarTabButton
              active={activeTab === "conversations"}
              onClick={() => setActiveTab("conversations")}
            >
              <MessageSquare className="h-3.5 w-3.5" />
              Яриа
            </SidebarTabButton>
            <SidebarTabButton
              active={activeTab === "reports"}
              onClick={() => {
                setActiveTab("reports");
                if (reports.length === 0) void loadReports();
              }}
            >
              <FileText className="h-3.5 w-3.5" />
              Тайлан
            </SidebarTabButton>
          </div>

          {activeTab === "conversations" ? (
            <ConversationsList
              items={conversations}
              loading={loadingConversations}
              activeId={conversationId}
              onPick={handleLoadConversation}
              onDelete={(c) => setConfirmDeleteConv(c)}
              onNew={handleNewConversation}
              onRefresh={() => void loadConversations()}
            />
          ) : (
            <ReportsList
              items={reports}
              loading={loadingReports}
              onDelete={(r) => setConfirmDeleteReport(r)}
              onRefresh={() => void loadReports()}
            />
          )}
        </aside>
      )}

      {/* Chat */}
      <div className="flex min-w-0 flex-1 flex-col overflow-hidden rounded-xl border border-border-light bg-card">
        <header className="flex items-center gap-2 border-b border-border-light px-3 py-2.5">
          <Button
            variant="outline"
            size="icon-sm"
            onClick={() => setShowSidebar((s) => !s)}
            aria-label="Түүх харах"
            className="hidden lg:inline-flex"
          >
            <ChevronLeft
              className={cn(
                "h-3.5 w-3.5 transition-transform",
                !showSidebar && "rotate-180"
              )}
            />
          </Button>
          <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-primary-300 via-primary-500 to-primary-700 text-white shadow-sm">
            <Bot className="h-4.5 w-4.5" />
          </div>
          <div className="min-w-0 flex-1">
            <h1 className="truncate text-[15px] font-semibold text-foreground">
              AI Бизнес Ажилтан
            </h1>
            <p className="flex items-center gap-1 text-[11px] text-muted-foreground">
              <span className="inline-block h-1.5 w-1.5 rounded-full bg-emerald-500" />
              Идэвхтэй
              {conversationId && (
                <span className="ml-2 inline-flex items-center gap-1 rounded-md bg-sky-100 px-1.5 py-0.5 text-[10px] font-medium text-sky-700 dark:bg-sky-500/15 dark:text-sky-300">
                  <CheckCircle2 className="h-3 w-3" />
                  Хадгалагдсан
                </span>
              )}
            </p>
          </div>
          <Button variant="outline" size="sm" onClick={handleNewConversation}>
            <Plus className="h-3.5 w-3.5" />
            Шинэ яриа
          </Button>
        </header>

        <div ref={scrollRef} className="flex-1 overflow-y-auto px-3 py-3">
          <ul className="space-y-3">
            {messages.map((m) => (
              <MessageItem key={m.id} message={m} />
            ))}

            {showQuickPrompts && (
              <li>
                <div className="ml-9 mt-1 grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">
                  {QUICK_PROMPTS.map((qp) => (
                    <button
                      key={qp.label}
                      type="button"
                      onClick={() => void send(qp.prompt)}
                      disabled={sending}
                      className={cn(
                        "flex items-center gap-1.5 rounded-lg border border-foreground/15 bg-foreground/[0.04] px-3 py-2 text-left text-[12px] font-medium text-foreground transition-colors",
                        "hover:border-primary-300 hover:bg-primary-50/60 hover:text-primary-700",
                        "disabled:cursor-not-allowed disabled:opacity-50"
                      )}
                    >
                      <span className="text-primary-600">{qp.icon}</span>
                      <span className="truncate">{qp.label}</span>
                    </button>
                  ))}
                </div>
              </li>
            )}

            {sending && (
              <li>
                <TypingBubble />
              </li>
            )}
          </ul>
        </div>

        <Composer
          value={input}
          onChange={setInput}
          onKeyDown={handleKeyDown}
          onSubmit={() => void send(input)}
          disabled={sending}
        />
      </div>

      <ConfirmDialog
        open={!!confirmDeleteConv}
        title="Ярианы түүхийг устгах уу?"
        description={
          confirmDeleteConv ? (
            <span>
              <strong>{confirmDeleteConv.title}</strong> ярианы түүхийг устгах
              гэж байна. Үүнийг буцаах боломжгүй.
            </span>
          ) : null
        }
        confirmLabel="Устгах"
        destructive
        onOpenChange={(o) => !o && setConfirmDeleteConv(null)}
        onConfirm={handleConfirmDeleteConv}
      />
      <ConfirmDialog
        open={!!confirmDeleteReport}
        title="Тайланг устгах уу?"
        description={
          confirmDeleteReport ? (
            <span>
              <strong>{confirmDeleteReport.title}</strong> тайланг устгах гэж
              байна.
            </span>
          ) : null
        }
        confirmLabel="Устгах"
        destructive
        onOpenChange={(o) => !o && setConfirmDeleteReport(null)}
        onConfirm={handleConfirmDeleteReport}
      />
    </div>
  );
}

function SidebarTabButton({
  active,
  onClick,
  children,
}: {
  active: boolean;
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "flex flex-1 items-center justify-center gap-1.5 px-3 py-2.5 text-[12px] font-medium transition-colors",
        active
          ? "border-b-2 border-primary text-primary-700"
          : "text-muted-foreground hover:text-foreground"
      )}
    >
      {children}
    </button>
  );
}

function ConversationsList({
  items,
  loading,
  activeId,
  onPick,
  onDelete,
  onNew,
  onRefresh,
}: {
  items: AiConversationListItem[];
  loading: boolean;
  activeId: string | null;
  onPick: (c: AiConversationListItem) => void;
  onDelete: (c: AiConversationListItem) => void;
  onNew: () => void;
  onRefresh: () => void;
}) {
  return (
    <>
      <div className="flex items-center justify-between border-b border-border-light px-3 py-2">
        <span className="text-[11px] text-muted-foreground">
          {items.length} яриа
        </span>
        <div className="flex items-center gap-1">
          <Button
            variant="outline"
            size="icon-sm"
            onClick={onRefresh}
            aria-label="Шинэчлэх"
          >
            <RefreshCw className={cn("h-3 w-3", loading && "animate-spin")} />
          </Button>
          <Button size="sm" onClick={onNew}>
            <Plus className="h-3 w-3" />
            Шинэ
          </Button>
        </div>
      </div>
      <div className="flex-1 overflow-y-auto px-2 py-2">
        {loading && items.length === 0 ? (
          <div className="flex items-center justify-center py-6">
            <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />
          </div>
        ) : items.length === 0 ? (
          <div className="flex flex-col items-center justify-center gap-2 py-8 text-muted-foreground">
            <MessageSquare className="h-6 w-6 opacity-60" />
            <p className="text-[11px]">Яриа байхгүй байна</p>
          </div>
        ) : (
          <ul className="space-y-1">
            {items.map((c) => {
              const active = activeId === c.id;
              return (
                <li key={c.id}>
                  <button
                    type="button"
                    onClick={() => onPick(c)}
                    className={cn(
                      "group flex w-full items-start gap-2 rounded-lg border px-2 py-1.5 text-left transition-colors",
                      active
                        ? "border-primary bg-primary-50"
                        : "border-transparent hover:bg-muted/60"
                    )}
                  >
                    <div className="min-w-0 flex-1">
                      <div
                        className={cn(
                          "truncate text-[12px] font-medium",
                          active ? "text-primary-700" : "text-foreground"
                        )}
                      >
                        {c.title}
                      </div>
                      <div className="mt-0.5 flex items-center gap-1 text-[10px] text-muted-foreground">
                        <MessageSquare className="h-2.5 w-2.5" />
                        {c.messageCount} мессеж
                        {c.updatedAt && (
                          <>
                            <span>·</span>
                            <Clock className="h-2.5 w-2.5" />
                            {formatSidebarDate(c.updatedAt)}
                          </>
                        )}
                      </div>
                    </div>
                    <span
                      onClick={(e) => {
                        e.stopPropagation();
                        onDelete(c);
                      }}
                      title="Устгах"
                      className="shrink-0 rounded p-1 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100 hover:bg-rose-50 hover:text-rose-600 dark:hover:bg-rose-500/10"
                    >
                      <Trash2 className="h-3 w-3" />
                    </span>
                  </button>
                </li>
              );
            })}
          </ul>
        )}
      </div>
    </>
  );
}

function ReportsList({
  items,
  loading,
  onDelete,
  onRefresh,
}: {
  items: AiReport[];
  loading: boolean;
  onDelete: (r: AiReport) => void;
  onRefresh: () => void;
}) {
  return (
    <>
      <div className="flex items-center justify-between border-b border-border-light px-3 py-2">
        <span className="text-[11px] text-muted-foreground">
          {items.length} тайлан
        </span>
        <Button
          variant="outline"
          size="icon-sm"
          onClick={onRefresh}
          aria-label="Шинэчлэх"
        >
          <RefreshCw className={cn("h-3 w-3", loading && "animate-spin")} />
        </Button>
      </div>
      <div className="flex-1 overflow-y-auto px-2 py-2">
        {loading && items.length === 0 ? (
          <div className="flex items-center justify-center py-6">
            <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />
          </div>
        ) : items.length === 0 ? (
          <div className="flex flex-col items-center justify-center gap-1 py-8 text-center text-muted-foreground">
            <FileText className="h-6 w-6 opacity-60" />
            <p className="text-[11px]">Тайлан байхгүй байна.</p>
            <p className="text-[10px]">AI-аас тайлан үүсгэхийг хүснэ үү.</p>
          </div>
        ) : (
          <ul className="space-y-1">
            {items.map((r) => (
              <li key={r.id}>
                <a
                  href={r.downloadUrl || r.url || "#"}
                  target="_blank"
                  rel="noreferrer"
                  className="group flex items-start gap-2 rounded-lg border border-transparent px-2 py-1.5 transition-colors hover:bg-muted/60"
                >
                  <FileText
                    className={cn(
                      "mt-0.5 h-4 w-4 shrink-0",
                      r.type === "word"
                        ? "text-sky-600"
                        : "text-rose-600"
                    )}
                  />
                  <div className="min-w-0 flex-1">
                    <div className="truncate text-[12px] font-medium text-foreground">
                      {r.title}
                    </div>
                    <div className="mt-0.5 text-[10px] text-muted-foreground">
                      {String(r.type).toUpperCase()} · {formatFileSize(r.size)}
                      {r.createdAt && (
                        <> · {formatSidebarDate(r.createdAt)}</>
                      )}
                    </div>
                  </div>
                  <span
                    onClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      onDelete(r);
                    }}
                    title="Устгах"
                    className="shrink-0 rounded p-1 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100 hover:bg-rose-50 hover:text-rose-600 dark:hover:bg-rose-500/10"
                  >
                    <Trash2 className="h-3 w-3" />
                  </span>
                </a>
              </li>
            ))}
          </ul>
        )}
      </div>
    </>
  );
}

function MessageItem({ message }: { message: LocalMessage }) {
  if (message.role === "user") {
    return (
      <li className="flex justify-end">
        <div className="max-w-[78%] space-y-1">
          <div className="rounded-2xl rounded-br-md bg-primary px-3.5 py-2 text-[13px] leading-relaxed text-primary-foreground">
            {message.content}
          </div>
          <div className="flex items-center justify-end gap-1 text-[10px] text-muted-foreground">
            <Clock className="h-2.5 w-2.5" />
            {message.time || ""}
          </div>
        </div>
      </li>
    );
  }
  return (
    <li className="flex items-start gap-2">
      <span className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-primary-400 via-primary-500 to-primary-700 text-white">
        <Bot className="h-3.5 w-3.5" />
      </span>
      <div className="max-w-[78%] space-y-1">
        <div className="rounded-2xl rounded-bl-md border border-border-light bg-card px-3.5 py-2 text-[13px] leading-relaxed text-foreground">
          <div
            className="prose-sm break-words"
            dangerouslySetInnerHTML={{
              __html: formatAiMessage(message.content),
            }}
          />
        </div>
        <div className="flex items-center gap-1 text-[10px] text-muted-foreground">
          <Clock className="h-2.5 w-2.5" />
          {message.time || ""}
          {message.model && (
            <span className="ml-1 rounded bg-muted px-1 py-0.5 font-mono text-[9px]">
              {message.model}
            </span>
          )}
        </div>
      </div>
    </li>
  );
}

function TypingBubble() {
  return (
    <div className="flex items-start gap-2">
      <span className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-primary-400 via-primary-500 to-primary-700 text-white">
        <Bot className="h-3.5 w-3.5" />
      </span>
      <div className="rounded-2xl rounded-bl-md border border-border-light bg-card px-3.5 py-2.5">
        <span className="inline-flex items-center gap-1.5">
          <Dot delay={0} />
          <Dot delay={0.15} />
          <Dot delay={0.3} />
          <span className="ml-1 text-[11px] text-muted-foreground">
            Боловсруулж байна…
          </span>
        </span>
      </div>
    </div>
  );
}

function Dot({ delay }: { delay: number }) {
  return (
    <span
      className="h-1.5 w-1.5 animate-pulse rounded-full bg-muted-foreground/70"
      style={{ animationDelay: `${delay}s` }}
    />
  );
}

function Composer({
  value,
  onChange,
  onKeyDown,
  onSubmit,
  disabled,
}: {
  value: string;
  onChange: (v: string) => void;
  onKeyDown: (e: KeyboardEvent<HTMLTextAreaElement>) => void;
  onSubmit: () => void;
  disabled: boolean;
}) {
  return (
    <div className="border-t border-border-light p-3">
      <div className="flex items-end gap-2 rounded-xl border border-foreground/15 bg-foreground/[0.04] p-2 focus-within:border-ring focus-within:bg-card focus-within:ring-3 focus-within:ring-ring/40">
        <Sparkles className="ml-1.5 mb-2 h-4 w-4 shrink-0 text-primary-500" />
        <textarea
          value={value}
          onChange={(e) => onChange(e.target.value)}
          onKeyDown={onKeyDown}
          placeholder="Мессеж бичих… (Enter = илгээх, Shift+Enter = шинэ мөр)"
          rows={1}
          disabled={disabled}
          className="max-h-32 flex-1 resize-none bg-transparent py-1.5 text-[13px] outline-none placeholder:text-muted-foreground/70 disabled:opacity-50"
        />
        <Button
          type="button"
          size="icon"
          className="h-8 w-8 shrink-0"
          disabled={!value.trim() || disabled}
          onClick={onSubmit}
          aria-label="Илгээх"
        >
          {disabled ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <Send className="h-3.5 w-3.5" />
          )}
        </Button>
      </div>
    </div>
  );
}

// admin/src/app/pages/ai-worker/ai-worker.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { UntypedFormBuilder, Validators, UntypedFormGroup, ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { SimplebarAngularModule } from 'simplebar-angular';
import { PagetitleComponent } from 'src/app/shared/ui/pagetitle/pagetitle.component';
import { OpenaiService, AiConversation, AiReport } from 'src/app/core/services/openai.service';
import { FormsModule } from '@angular/forms';

interface ChatMessage {
  sender: 'user' | 'ai';
  message: string;
  time: string;
  model?: string;
}

@Component({
  selector: 'app-ai-worker',
  templateUrl: './ai-worker.component.html',
  styleUrls: ['./ai-worker.component.scss'],
  standalone: true,
  imports: [PagetitleComponent, CommonModule, SimplebarAngularModule, ReactiveFormsModule, FormsModule]
})
export class AiWorkerComponent implements OnInit {

  @ViewChild('chatScrollbar') chatScrollbar: any;

  breadCrumbItems: Array<{}>;
  chatForm: UntypedFormGroup;
  messages: ChatMessage[] = [];
  isTyping = false;
  currentConversationId: string | null = null;

  // Sidebar
  conversations: AiConversation[] = [];
  showHistory = true;
  loadingHistory = false;

  // Reports
  reports: AiReport[] = [];
  activeTab: 'conversations' | 'reports' = 'conversations';

  // Quick prompts
  quickPrompts = [
    { icon: 'bx-bar-chart-alt-2', label: 'Өнөөдрийн тайлан', prompt: 'Өнөөдрийн бизнесийн товч тайлан гаргаж өгнө үү.' },
    { icon: 'bx-trending-up', label: 'Сарын шинжилгээ', prompt: 'Энэ сарын борлуулалтын шинжилгээ хийж, өмнөх сартай харьцуулна уу.' },
    { icon: 'bx-group', label: 'Топ хэрэглэгчид', prompt: 'Хамгийн их алт эзэмшдэг топ 20 хэрэглэгчийн Pareto шинжилгээ хийнэ үү.' },
    { icon: 'bx-file', label: 'PDF тайлан', prompt: 'Энэ сарын бизнесийн гүйцэтгэлийн дэлгэрэнгүй PDF тайлан үүсгэнэ үү.' },
    { icon: 'bx-transfer-alt', label: 'Мөнгөн зарлага', prompt: 'Хүлээгдэж буй зарлагын хүсэлтүүдийг шинжилж, эрсдэлийн үнэлгээ хийнэ үү.' },
    { icon: 'bx-line-chart', label: 'KPI Dashboard', prompt: 'Бидний гол KPI үзүүлэлтүүдийг (DAU, ARPU, Retention, Conversion) тооцоолж, хүснэгтээр харуулна уу.' },
  ];

  constructor(
    private formBuilder: UntypedFormBuilder,
    private openaiService: OpenaiService
  ) {}

  ngOnInit() {
    this.breadCrumbItems = [{ label: 'Onegram' }, { label: 'AI Ажилтан', active: true }];
    this.chatForm = this.formBuilder.group({
      message: ['', [Validators.required]],
    });
    this.messages.push({
      sender: 'ai',
      message: 'Сайн байна уу! Би таны **AI бизнес туслах ажилтан**. GrammGold-ын бүх бизнес мэдээлэлд хандах боломжтой.\n\n🔍 **Миний чадварууд:**\n• Бизнесийн тайлан гаргах (PDF, Word)\n• Борлуулалт, хэрэглэгчийн шинжилгээ\n• KPI тооцоолол, MoM өсөлт\n• Хэрэглэгчийн дэлгэрэнгүй мэдээлэл хайх\n• Стратегийн зөвлөгөө өгөх\n\nДоорх товчлууруудаас сонгох эсвэл өөрийн асуултаа бичнэ үү! 👇',
      time: this.getCurrentTime()
    });
    this.loadConversations();
    this.loadReports();
  }

  get form() { return this.chatForm.controls; }

  getCurrentTime(): string {
    const now = new Date();
    return now.getHours().toString().padStart(2, '0') + ':' + now.getMinutes().toString().padStart(2, '0');
  }

  formatMessage(text: string): string {
    if (!text) return '';
    let html = text
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      // Bold
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      // Italic
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      // Inline code
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      // Headers
      .replace(/^### (.+)$/gm, '<h6 class="mt-2 mb-1">$1</h6>')
      .replace(/^## (.+)$/gm, '<h5 class="mt-3 mb-1">$1</h5>')
      .replace(/^# (.+)$/gm, '<h4 class="mt-3 mb-2">$1</h4>')
      // Horizontal rule
      .replace(/^---$/gm, '<hr class="my-2">')
      // Table support
      .replace(/^\|(.+)\|$/gm, (match) => {
        const cells = match.split('|').filter(c => c.trim());
        if (cells.every(c => /^[\s-:]+$/.test(c))) return '<!--table-sep-->';
        const cellHtml = cells.map(c => `<td class="px-2 py-1 border">${c.trim()}</td>`).join('');
        return `<tr>${cellHtml}</tr>`;
      });
    // Wrap consecutive table rows in table
    html = html.replace(/((?:<tr>.*<\/tr>\n?)+)/g, (match) => {
      const cleaned = match.replace(/<!--table-sep-->\n?/g, '');
      if (!cleaned.trim()) return '';
      const rows = cleaned.trim().split('\n').filter(r => r.trim());
      if (rows.length === 0) return '';
      const headerRow = rows[0].replace(/<td/g, '<th').replace(/<\/td>/g, '</th>');
      const bodyRows = rows.slice(1).join('\n');
      return `<div class="table-responsive my-2"><table class="table table-sm table-bordered mb-0"><thead class="table-light">${headerRow}</thead><tbody>${bodyRows}</tbody></table></div>`;
    });
    // Line breaks
    html = html.replace(/\n/g, '<br>');
    // Clean up extra <br> around block elements
    html = html.replace(/<br>\s*(<h[456]|<hr|<div|<table)/g, '$1');
    html = html.replace(/(<\/h[456]>|<\/div>|<\/table>)\s*<br>/g, '$1');
    return html;
  }

  useQuickPrompt(prompt: string) {
    this.chatForm.patchValue({ message: prompt });
    this.sendMessage();
  }

  async sendMessage() {
    if (this.chatForm.invalid) return;
    const messageText = this.chatForm.get('message').value.trim();
    if (!messageText) return;

    this.messages.push({ sender: 'user', message: messageText, time: this.getCurrentTime() });
    this.chatForm.reset();
    this.scrollToBottom();
    this.isTyping = true;

    try {
      const result = await this.openaiService.sendMessage(messageText, this.currentConversationId);
      this.currentConversationId = result.conversationId;
      this.messages.push({
        sender: 'ai', message: result.message, time: this.getCurrentTime(), model: result.model
      });
      this.loadConversations();
      // Check if response contains report links
      if (result.message && (result.message.includes('storage.googleapis.com') || result.message.includes('report'))) {
        this.loadReports();
      }
    } catch (error) {
      this.messages.push({
        sender: 'ai',
        message: '❌ Уучлаарай, алдаа гарлаа. Дахин оролдоно уу.\n\n`' + (error as Error).message + '`',
        time: this.getCurrentTime()
      });
    } finally {
      this.isTyping = false;
      this.scrollToBottom();
    }
  }

  scrollToBottom() {
    setTimeout(() => {
      if (this.chatScrollbar) {
        const el = this.chatScrollbar.SimpleBar.getScrollElement();
        el.scrollTop = el.scrollHeight;
      }
    }, 100);
  }

  // Sidebar methods
  async loadConversations() {
    try {
      this.conversations = await this.openaiService.getConversations();
    } catch (e) {
      console.error('Failed to load conversations', e);
    }
  }

  async loadReports() {
    try {
      this.reports = await this.openaiService.getReports();
    } catch (e) {
      console.error('Failed to load reports', e);
    }
  }

  toggleHistory() {
    this.showHistory = !this.showHistory;
    if (this.showHistory && this.activeTab === 'reports' && this.reports.length === 0) {
      this.loadReports();
    }
  }

  switchTab(tab: 'conversations' | 'reports') {
    this.activeTab = tab;
    if (tab === 'reports' && this.reports.length === 0) {
      this.loadReports();
    }
  }

  newConversation() {
    this.currentConversationId = null;
    this.messages = [{
      sender: 'ai',
      message: '🆕 Шинэ яриа эхэлж байна. Танд юугаар туслах вэ?',
      time: this.getCurrentTime()
    }];
  }

  async loadConversation(conv: AiConversation) {
    this.loadingHistory = true;
    try {
      const data = await this.openaiService.getConversation(conv.id);
      this.currentConversationId = conv.id;
      this.messages = data.messages.map(msg => ({
        sender: msg.role === 'user' ? 'user' as const : 'ai' as const,
        message: msg.content,
        time: msg.timestamp ? new Date(msg.timestamp).toLocaleTimeString('mn-MN', { hour: '2-digit', minute: '2-digit' }) : ''
      }));
      this.scrollToBottom();
    } catch (e) {
      console.error('Failed to load conversation', e);
    } finally {
      this.loadingHistory = false;
    }
  }

  async deleteConversation(event: Event, conv: AiConversation) {
    event.stopPropagation();
    if (!confirm('Энэ ярианы түүхийг устгах уу?')) return;
    try {
      await this.openaiService.deleteConversation(conv.id);
      if (this.currentConversationId === conv.id) this.newConversation();
      this.loadConversations();
    } catch (e) {
      console.error('Failed to delete conversation', e);
    }
  }

  async deleteReport(event: Event, report: AiReport) {
    event.stopPropagation();
    if (!confirm('Энэ тайланг устгах уу?')) return;
    try {
      await this.openaiService.deleteReport(report.id);
      this.loadReports();
    } catch (e) {
      console.error('Failed to delete report', e);
    }
  }

  downloadReport(report: AiReport) {
    window.open(report.downloadUrl, '_blank');
  }

  formatFileSize(bytes: number): string {
    if (!bytes) return '0 B';
    const k = 1024;
    const sizes = ['B', 'KB', 'MB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
  }

  formatDate(dateStr: string): string {
    if (!dateStr) return '';
    const d = new Date(dateStr);
    const month = d.getMonth() + 1;
    const day = d.getDate();
    const hours = d.getHours().toString().padStart(2, '0');
    const mins = d.getMinutes().toString().padStart(2, '0');
    return `${month}/${day} ${hours}:${mins}`;
  }

  onKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      this.sendMessage();
    }
  }
}

<div class="container-fluid">
  <app-page-title title="AI Ажилтан" [breadcrumbItems]="breadCrumbItems"></app-page-title>

  <div class="row">
    <!-- Sidebar -->
    <div class="col-lg-3" *ngIf="showHistory">
      <div class="card sidebar-card">
        <div class="card-body p-0">
          <!-- Sidebar Tabs -->
          <div class="sidebar-tabs">
            <button class="sidebar-tab" [class.active]="activeTab === 'conversations'" (click)="switchTab('conversations')">
              <i class="bx bx-chat me-1"></i> Яриа
            </button>
            <button class="sidebar-tab" [class.active]="activeTab === 'reports'" (click)="switchTab('reports')">
              <i class="bx bx-file me-1"></i> Тайлан
            </button>
          </div>

          <!-- Conversations Tab -->
          <div class="sidebar-content" *ngIf="activeTab === 'conversations'">
            <div class="d-flex justify-content-between align-items-center p-3 pb-2">
              <span class="text-muted font-size-12">{{ conversations.length }} яриа</span>
              <button class="btn btn-primary btn-sm" (click)="newConversation()">
                <i class="bx bx-plus me-1"></i> Шинэ
              </button>
            </div>

            @if (loadingHistory) {
              <div class="text-center py-3">
                <div class="spinner-border spinner-border-sm text-primary" role="status"></div>
              </div>
            }

            <ngx-simplebar style="height: calc(100vh - 320px);">
              <ul class="list-unstyled mb-0 px-2">
                @for (conv of conversations; track conv.id) {
                  <li class="conversation-item p-2 rounded mb-1"
                      [class.active]="currentConversationId === conv.id"
                      (click)="loadConversation(conv)">
                    <div class="d-flex justify-content-between align-items-start">
                      <div class="flex-grow-1 overflow-hidden me-2">
                        <h6 class="text-truncate font-size-13 mb-1">{{ conv.title }}</h6>
                        <p class="text-muted font-size-11 mb-0">
                          <i class="bx bx-message-detail me-1"></i>{{ conv.messageCount }} мессеж
                          <span class="ms-2" *ngIf="conv.updatedAt">· {{ formatDate(conv.updatedAt) }}</span>
                        </p>
                      </div>
                      <button class="btn btn-link btn-sm text-danger p-0 delete-btn" (click)="deleteConversation($event, conv)"
                        title="Устгах">
                        <i class="bx bx-trash font-size-14"></i>
                      </button>
                    </div>
                  </li>
                }
                @if (conversations.length === 0) {
                  <li class="text-center text-muted py-4">
                    <i class="bx bx-chat font-size-24 d-block mb-2"></i>
                    Яриа байхгүй байна
                  </li>
                }
              </ul>
            </ngx-simplebar>
          </div>

          <!-- Reports Tab -->
          <div class="sidebar-content" *ngIf="activeTab === 'reports'">
            <div class="p-3 pb-2">
              <span class="text-muted font-size-12">{{ reports.length }} тайлан</span>
            </div>
            <ngx-simplebar style="height: calc(100vh - 320px);">
              <ul class="list-unstyled mb-0 px-2">
                @for (report of reports; track report.id) {
                  <li class="report-item p-2 rounded mb-1" (click)="downloadReport(report)">
                    <div class="d-flex align-items-start">
                      <div class="report-icon me-2">
                        <i class="bx font-size-20" [class.bx-file-blank]="report.type === 'pdf'" [class.bxs-file-doc]="report.type === 'word'"
                          [class.text-danger]="report.type === 'pdf'" [class.text-primary]="report.type === 'word'"></i>
                      </div>
                      <div class="flex-grow-1 overflow-hidden me-2">
                        <h6 class="text-truncate font-size-13 mb-1">{{ report.title }}</h6>
                        <p class="text-muted font-size-11 mb-0">
                          {{ report.type | uppercase }} · {{ formatFileSize(report.size) }}
                          <span *ngIf="report.createdAt"> · {{ formatDate(report.createdAt) }}</span>
                        </p>
                      </div>
                      <button class="btn btn-link btn-sm text-danger p-0 delete-btn" (click)="deleteReport($event, report)"
                        title="Устгах">
                        <i class="bx bx-trash font-size-14"></i>
                      </button>
                    </div>
                  </li>
                }
                @if (reports.length === 0) {
                  <li class="text-center text-muted py-4">
                    <i class="bx bx-file font-size-24 d-block mb-2"></i>
                    Тайлан байхгүй байна.<br>
                    <span class="font-size-12">AI-аас тайлан үүсгэхийг хүснэ үү.</span>
                  </li>
                }
              </ul>
            </ngx-simplebar>
          </div>
        </div>
      </div>
    </div>

    <!-- Chat Area -->
    <div [class]="showHistory ? 'col-lg-9' : 'col-lg-12'">
      <div class="card chat-card">
        <div class="card-body p-0">
          <!-- Chat Header -->
          <div class="chat-header p-3 border-bottom">
            <div class="d-flex align-items-center">
              <button class="btn btn-light btn-sm me-3" (click)="toggleHistory()"
                [class.btn-soft-primary]="showHistory" title="Түүх харах">
                <i class="bx bx-menu-alt-left font-size-16"></i>
              </button>
              <div class="flex-shrink-0 me-3">
                <div class="avatar-sm">
                  <span class="avatar-title rounded-circle bg-primary bg-gradient font-size-20">
                    <i class="bx bx-bot"></i>
                  </span>
                </div>
              </div>
              <div class="flex-grow-1">
                <h5 class="font-size-15 mb-0">AI Бизнес Ажилтан</h5>
                <p class="text-muted mb-0 font-size-12">
                  <i class="mdi mdi-circle text-success align-middle me-1"></i> Идэвхтэй
                  <span class="ms-1 badge bg-info-subtle text-info" *ngIf="currentConversationId">
                    <i class="bx bx-save me-1"></i>Хадгалагдсан
                  </span>
                </p>
              </div>
              <button class="btn btn-soft-primary btn-sm" (click)="newConversation()">
                <i class="bx bx-plus me-1"></i> Шинэ яриа
              </button>
            </div>
          </div>

          <!-- Chat Messages -->
          <div class="chat-conversation">
            <ngx-simplebar style="height: calc(100vh - 340px); min-height: 400px;" #chatScrollbar>
              <ul class="list-unstyled mb-0 p-3">
                @for (msg of messages; track $index) {
                  <li [class]="msg.sender === 'user' ? 'right' : ''">
                    <div class="conversation-list">
                      <div class="d-flex">
                        @if (msg.sender === 'ai') {
                          <div class="flex-shrink-0 me-3">
                            <div class="avatar-xs">
                              <span class="avatar-title rounded-circle bg-primary bg-gradient">
                                <i class="bx bx-bot"></i>
                              </span>
                            </div>
                          </div>
                        }
                        <div class="flex-grow-1">
                          <div class="ctext-wrap" [class.ai-message]="msg.sender === 'ai'">
                            <div class="conversation-name">
                              {{ msg.sender === 'ai' ? 'AI Ажилтан' : 'Та' }}
                            </div>
                            @if (msg.sender === 'ai') {
                              <div class="mb-0 message-content" [innerHTML]="formatMessage(msg.message)"></div>
                            } @else {
                              <p class="mb-0 message-content">{{ msg.message }}</p>
                            }
                          </div>
                          <p class="chat-time mb-0 mt-1">
                            <i class="bx bx-time-five align-middle me-1"></i> {{ msg.time }}
                            <span class="ms-2 badge bg-light text-muted" *ngIf="msg.model">{{ msg.model }}</span>
                          </p>
                        </div>
                      </div>
                    </div>
                  </li>
                }

                <!-- Quick Prompts (show only when messages are few) -->
                @if (messages.length <= 1 && !isTyping) {
                  <li>
                    <div class="quick-prompts mt-3">
                      <div class="row g-2">
                        @for (qp of quickPrompts; track qp.label) {
                          <div class="col-md-4 col-6">
                            <button class="btn btn-outline-primary btn-sm w-100 text-start quick-prompt-btn"
                              (click)="useQuickPrompt(qp.prompt)">
                              <i class="bx {{ qp.icon }} me-1"></i> {{ qp.label }}
                            </button>
                          </div>
                        }
                      </div>
                    </div>
                  </li>
                }

                @if (isTyping) {
                  <li>
                    <div class="conversation-list">
                      <div class="d-flex">
                        <div class="flex-shrink-0 me-3">
                          <div class="avatar-xs">
                            <span class="avatar-title rounded-circle bg-primary bg-gradient">
                              <i class="bx bx-bot"></i>
                            </span>
                          </div>
                        </div>
                        <div class="flex-grow-1">
                          <div class="ctext-wrap ai-message">
                            <div class="conversation-name">AI Ажилтан</div>
                            <div class="typing-wrapper">
                              <span class="typing-indicator">
                                <span class="dot"></span>
                                <span class="dot"></span>
                                <span class="dot"></span>
                              </span>
                              <span class="typing-text ms-2">Боловсруулж байна...</span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>
                }
              </ul>
            </ngx-simplebar>
          </div>

          <!-- Chat Input -->
          <div class="chat-input p-3 border-top">
            <form [formGroup]="chatForm" (ngSubmit)="sendMessage()">
              <div class="d-flex align-items-end gap-2">
                <div class="flex-grow-1">
                  <textarea class="form-control chat-textarea" placeholder="Мессеж бичих... (Enter = илгээх, Shift+Enter = шинэ мөр)"
                    formControlName="message" (keydown)="onKeydown($event)" autocomplete="off"
                    [disabled]="isTyping" rows="1"></textarea>
                </div>
                <button type="submit" class="btn btn-primary btn-rounded chat-send-btn" [disabled]="isTyping || chatForm.invalid">
                  @if (isTyping) {
                    <div class="spinner-border spinner-border-sm" role="status"></div>
                  } @else {
                    <i class="mdi mdi-send font-size-18"></i>
                  }
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
