// admin/src/app/pages/gift-orders/gift-orders.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { BsDropdownModule } from 'ngx-bootstrap/dropdown';
import firebase from 'firebase/compat/app';
import 'firebase/compat/firestore';
import Swal from 'sweetalert2';
import * as XLSX from 'xlsx';

@Component({
  selector: 'app-gift-orders',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    BsDropdownModule
  ],
  templateUrl: './gift-orders.component.html',
  styleUrl: './gift-orders.component.css'
})
export class GiftOrdersComponent implements OnInit {

  // Gift orders data
  giftOrders: any[] = [];
  allGiftOrders: any[] = [];
  filteredGiftOrders: any[] = [];
  isLoading: boolean = false;
  searchTerm: string = '';
  
  // Filtering properties
  statusFilter: string = '';
  metalFilter: string = '';
  dateFilter: string = '';
  
  // Pagination properties
  currentPage: number = 1;
  itemsPerPage: number = 20;
  totalItems: number = 0;
  totalPages: number = 0;
  startItem: number = 0;
  endItem: number = 0;
  
  // Sorting properties
  sortField: string = 'created_at';
  sortDirection: 'asc' | 'desc' = 'desc';

  constructor() { }

  ngOnInit(): void {
    this.fetchGiftOrders();
  }

  /**
   * Fetch gift orders from Firestore
   */
  async fetchGiftOrders() {
    this.isLoading = true;
    try {
      const giftOrdersSnapshot = await firebase.firestore().collection('gift_orders').get();
      this.allGiftOrders = giftOrdersSnapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      }));
      
      this.searchGiftOrders();
      console.log('Gift orders loaded:', this.allGiftOrders.length);
    } catch (error) {
      console.error('Error fetching gift orders:', error);
      Swal.fire({
        title: 'Алдаа!',
        text: 'Бэлгийн захиалгуудын мэдээлэл татахад алдаа гарлаа.',
        icon: 'error'
      });
    } finally {
      this.isLoading = false;
    }
  }

  /**
   * Search gift orders
   */
  searchGiftOrders() {
    let filteredOrders = this.allGiftOrders;

    // Filter by search term
    if (this.searchTerm) {
      filteredOrders = filteredOrders.filter(order => 
        (order.sender?.first_name?.toLowerCase().includes(this.searchTerm.toLowerCase())) ||
        (order.sender?.last_name?.toLowerCase().includes(this.searchTerm.toLowerCase())) ||
        (order.receiver?.first_name?.toLowerCase().includes(this.searchTerm.toLowerCase())) ||
        (order.receiver?.last_name?.toLowerCase().includes(this.searchTerm.toLowerCase())) ||
        (order.sender?.phone?.includes(this.searchTerm)) ||
        (order.receiver?.phone?.includes(this.searchTerm)) ||
        (order.id?.toLowerCase().includes(this.searchTerm.toLowerCase())) ||
        (order.greeting?.toLowerCase().includes(this.searchTerm.toLowerCase()))
      );
    }

    // Filter by status
    if (this.statusFilter) {
      filteredOrders = filteredOrders.filter(order => 
        order.status === this.statusFilter
      );
    }

    // Filter by metal type
    if (this.metalFilter) {
      filteredOrders = filteredOrders.filter(order => {
        if (this.metalFilter === 'gold') {
          return order.metal_id === 1;
        } else if (this.metalFilter === 'silver') {
          return order.metal_id === 3;
        }
        return true;
      });
    }

    // Filter by date
    if (this.dateFilter) {
      filteredOrders = filteredOrders.filter(order => {
        if (order.created_at) {
          const orderDate = new Date(order.created_at.toDate());
          const filterDate = new Date(this.dateFilter);
          
          return orderDate.toDateString() === filterDate.toDateString();
        }
        return false;
      });
    }

    this.filteredGiftOrders = filteredOrders;
    
    // Apply sorting
    this.applySorting();
    
    this.totalItems = this.filteredGiftOrders.length;
    this.currentPage = 1;
    this.updatePagination();
  }

  /**
   * Apply current sorting to filtered orders
   */
  applySorting() {
    if (this.sortField) {
      this.filteredGiftOrders.sort((a, b) => {
        let aValue = this.getSortValue(a, this.sortField);
        let bValue = this.getSortValue(b, this.sortField);

        if (aValue < bValue) {
          return this.sortDirection === 'asc' ? -1 : 1;
        }
        if (aValue > bValue) {
          return this.sortDirection === 'asc' ? 1 : -1;
        }
        return 0;
      });
    }
  }

  /**
   * Get sort value for comparison
   */
  getSortValue(order: any, field: string): any {
    switch (field) {
      case 'sender_name':
        return `${order.sender?.first_name || ''} ${order.sender?.last_name || ''}`.toLowerCase();
      case 'receiver_name':
        return `${order.receiver?.first_name || ''} ${order.receiver?.last_name || ''}`.toLowerCase();
      case 'quantity':
        return order.quantity || 0;
      case 'created_at':
        return order.created_at?.toDate() || new Date(0);
      case 'status':
        return order.status || '';
      default:
        return order[field] || '';
    }
  }

  /**
   * Sort orders
   */
  sortOrders(field: string) {
    if (this.sortField === field) {
      this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortField = field;
      this.sortDirection = 'asc';
    }

    this.applySorting();
    this.updatePagination();
  }

  /**
   * Get sort icon class
   */
  getSortIcon(field: string): string {
    if (this.sortField !== field) {
      return 'mdi mdi-sort';
    }
    return this.sortDirection === 'asc' ? 'mdi mdi-sort-ascending' : 'mdi mdi-sort-descending';
  }

  /**
   * Update pagination
   */
  updatePagination() {
    this.totalPages = Math.ceil(this.totalItems / this.itemsPerPage);
    this.startItem = (this.currentPage - 1) * this.itemsPerPage + 1;
    this.endItem = Math.min(this.currentPage * this.itemsPerPage, this.totalItems);
    
    const startIndex = (this.currentPage - 1) * this.itemsPerPage;
    const endIndex = startIndex + this.itemsPerPage;
    this.giftOrders = this.filteredGiftOrders.slice(startIndex, endIndex);
  }

  /**
   * Go to specific page
   */
  goToPage(page: number) {
    if (page >= 1 && page <= this.totalPages) {
      this.currentPage = page;
      this.updatePagination();
    }
  }

  /**
   * Go to previous page
   */
  previousPage() {
    if (this.currentPage > 1) {
      this.currentPage--;
      this.updatePagination();
    }
  }

  /**
   * Go to next page
   */
  nextPage() {
    if (this.currentPage < this.totalPages) {
      this.currentPage++;
      this.updatePagination();
    }
  }

  /**
   * Get page numbers for pagination
   */
  getPageNumbers(): number[] {
    const pages: number[] = [];
    const maxPages = 5;
    let startPage = Math.max(1, this.currentPage - Math.floor(maxPages / 2));
    let endPage = Math.min(this.totalPages, startPage + maxPages - 1);

    if (endPage - startPage < maxPages - 1) {
      startPage = Math.max(1, endPage - maxPages + 1);
    }

    for (let i = startPage; i <= endPage; i++) {
      pages.push(i);
    }

    return pages;
  }

  /**
   * Select status filter
   */
  selectStatusFilter(event: any) {
    this.statusFilter = event.target.value;
    this.searchGiftOrders();
  }

  /**
   * Select metal filter
   */
  selectMetalFilter(event: any) {
    this.metalFilter = event.target.value;
    this.searchGiftOrders();
  }

  /**
   * Filter by date
   */
  filterByDate() {
    this.searchGiftOrders();
  }

  /**
   * Clear date filter
   */
  clearDateFilter() {
    this.dateFilter = '';
    this.searchGiftOrders();
  }

  /**
   * Refresh gift orders
   */
  refreshGiftOrders() {
    this.fetchGiftOrders();
  }

  /**
   * Format timestamp
   */
  formatTimestamp(timestamp: any): string {
    if (!timestamp) return 'Байхгүй';
    
    try {
      const date = timestamp.toDate();
      return date.toLocaleDateString('mn-MN') + ' ' + date.toLocaleTimeString('mn-MN');
    } catch (error) {
      return 'Алдаатай огноо';
    }
  }

  /**
   * Get sender full name
   */
  getSenderName(order: any): string {
    const firstName = order.sender?.first_name || '';
    const lastName = order.sender?.last_name || '';
    return `${lastName} ${firstName}`.trim() || 'Байхгүй';
  }

  /**
   * Get receiver full name
   */
  getReceiverName(order: any): string {
    const firstName = order.receiver?.first_name || '';
    const lastName = order.receiver?.last_name || '';
    return `${lastName} ${firstName}`.trim() || 'Байхгүй';
  }

  /**
   * Get metal type name
   */
  getMetalTypeName(metalId: number): string {
    return metalId === 1 ? 'Алт' : metalId === 3 ? 'Мөнгө' : 'Тодорхойгүй';
  }

  /**
   * Get status badge class
   */
  getStatusBadgeClass(status: string): string {
    switch (status) {
      case 'pending':
        return 'badge bg-warning';
      case 'sent':
        return 'badge bg-info';
      case 'received':
        return 'badge bg-success';
      case 'cancelled':
        return 'badge bg-danger';
      default:
        return 'badge bg-secondary';
    }
  }

  /**
   * Get status text
   */
  getStatusText(status: string): string {
    switch (status) {
      case 'pending':
        return 'Хүлээгдэж буй';
      case 'sent':
        return 'Илгээгдсэн';
      case 'received':
        return 'Хүлээн авсан';
      case 'cancelled':
        return 'Цуцалсан';
      default:
        return status || 'Тодорхойгүй';
    }
  }

  /**
   * Track by function for ngFor
   */
  trackByGiftOrder(index: number, order: any): any {
    return order.id;
  }

  /**
   * Export to Excel
   */
  exportToExcel() {
    try {
      if (this.filteredGiftOrders.length === 0) {
        Swal.fire({
          title: 'Анхааруулга!',
          text: 'Экспорт хийх бэлгийн захиалга байхгүй байна.',
          icon: 'warning'
        });
        return;
      }

      Swal.fire({
        title: 'Боловсруулж байна...',
        text: 'Excel файл үүсгэж байна.',
        allowOutsideClick: false,
        didOpen: () => {
          Swal.showLoading();
        }
      });

      const excelData = this.filteredGiftOrders.map((order) => ({
        'Бэлгийн захиалгын ID': order.id || '',
        'Илгээгч нэр': this.getSenderName(order),
        'Илгээгч утас': order.sender?.phone || 'Байхгүй',
        'Илгээгч и-мэйл': order.sender?.email || 'Байхгүй',
        'Хүлээн авагч нэр': this.getReceiverName(order),
        'Хүлээн авагч утас': order.receiver?.phone || 'Байхгүй',
        'Хүлээн авагч и-мэйл': order.receiver?.email || 'Байхгүй',
        'Металл төрөл': this.getMetalTypeName(order.metal_id),
        'Тоо хэмжээ': order.quantity || 0,
        'Мэндчилгээ': order.greeting || 'Байхгүй',
        'Төлөв': this.getStatusText(order.status),
        'Үүсгэсэн огноо': this.formatTimestamp(order.created_at),
        'Шинэчилсэн огноо': this.formatTimestamp(order.updated_at),
        'Цуцалсан огноо': this.formatTimestamp(order.cancelled_at),
        'Хүлээн авсан огноо': this.formatTimestamp(order.received_at)
      }));

      const wb = XLSX.utils.book_new();
      const ws = XLSX.utils.json_to_sheet(excelData);

      const colWidths = [
        { wch: 25 }, // ID
        { wch: 20 }, // Илгээгч нэр
        { wch: 15 }, // Илгээгч утас
        { wch: 25 }, // Илгээгч и-мэйл
        { wch: 20 }, // Хүлээн авагч нэр
        { wch: 15 }, // Хүлээн авагч утас
        { wch: 25 }, // Хүлээн авагч и-мэйл
        { wch: 12 }, // Металл төрөл
        { wch: 12 }, // Тоо хэмжээ
        { wch: 30 }, // Мэндчилгээ
        { wch: 15 }, // Төлөв
        { wch: 20 }, // Үүсгэсэн огноо
        { wch: 20 }, // Шинэчилсэн огноо
        { wch: 20 }, // Цуцалсан огноо
        { wch: 20 }  // Хүлээн авсан огноо
      ];
      ws['!cols'] = colWidths;

      XLSX.utils.book_append_sheet(wb, ws, 'Бэлгийн захиалгууд');

      const currentDate = new Date().toISOString().split('T')[0];
      const filename = `Бэлгийн_захиалгуудын_жагсаалт_${currentDate}.xlsx`;

      XLSX.writeFile(wb, filename);

      Swal.fire({
        title: 'Амжилттай!',
        html: `
          <p>Excel файл амжилттай үүсгэгдлээ.</p>
          <div class="text-start mt-3">
            <small class="text-muted">
              <strong>Файлын нэр:</strong> ${filename}<br>
              <strong>Экспорт хийсэн захиалгын тоо:</strong> ${excelData.length}<br>
              <strong>Нийт захиалгын тоо:</strong> ${this.allGiftOrders.length}<br>
              <strong>Огноо:</strong> ${new Date().toLocaleString('mn-MN')}
            </small>
          </div>
        `,
        icon: 'success',
        timer: 4000,
        showConfirmButton: true
      });

    } catch (error) {
      console.error('Excel export error:', error);
      Swal.fire({
        title: 'Алдаа!',
        text: 'Excel файл үүсгэхэд алдаа гарлаа.',
        icon: 'error'
      });
    }
  }
}

<!-- Start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0 font-size-18">Бэлгийн захиалгууд</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Бэлгийн захиалгууд</a></li>
                    <li class="breadcrumb-item active">Жагсаалт</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body border-bottom">
                <div class="d-flex align-items-center">
                    <h5 class="mb-0 card-title flex-grow-1">Бэлгийн захиалгын жагсаалт</h5>
                    <div class="flex-shrink-0 d-flex gap-1">
                        <a href="javascript:void(0);" class="btn btn-primary"
                            style="background-color: #1D6F42; border-color: #1D6F42;" (click)="exportToExcel()">
                            <i class="mdi mdi-file-excel"></i>Excel Export
                        </a>
                        <a href="javascript:void(0);" class="btn btn-light" (click)="refreshGiftOrders()">
                            <i class="mdi mdi-refresh"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <!-- Search and filters -->
                <div class="row mb-3">
                    <div class="col-lg-4">
                        <div class="form-group">
                            <label class="form-label">Хайх</label>
                            <input type="text" class="form-control"
                                placeholder="Илгээгч/хүлээн авагчийн нэр, утас, мэндчилгээ..." [(ngModel)]="searchTerm"
                                (keyup)="searchGiftOrders()" name="searchTerm">
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label class="form-label">Төлөв</label>
                            <select class="form-select" (change)="selectStatusFilter($event)"
                                name="statusFilter" [(ngModel)]="statusFilter">
                                <option value="">Бүгд</option>
                                <option value="pending">Хүлээгдэж буй</option>
                                <option value="received">Хүлээн авсан</option>
                                <option value="cancelled">Цуцалсан</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label class="form-label">Металл төрөл</label>
                            <select class="form-select" (change)="selectMetalFilter($event)" name="metalFilter"
                                [(ngModel)]="metalFilter">
                                <option value="">Бүгд</option>
                                <option value="gold">Алт</option>
                                <option value="silver">Мөнгө</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label class="form-label">Огнооны шүүлт</label>
                            <div class="input-group">
                                <input type="date" class="form-control" [(ngModel)]="dateFilter"
                                    (change)="filterByDate()" name="dateFilter">
                                <button class="btn btn-outline-secondary" type="button" (click)="clearDateFilter()"
                                    [disabled]="!dateFilter">
                                    <i class="mdi mdi-close"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Stats info -->
                <div class="row mb-3">
                    <div class="col-lg-6">
                        <p class="text-muted mb-2">
                            <i class="mdi mdi-information-outline me-1"></i>
                            Нийт: {{ totalItems }} бэлгийн захиалга
                            <span *ngIf="searchTerm || statusFilter || metalFilter || dateFilter">(шүүлтийн дүн)</span>
                        </p>
                    </div>
                </div>

                <!-- Loading state -->
                <div *ngIf="isLoading" class="text-center py-5">
                    <div class="spinner-border text-primary" role="status">
                        <span class="visually-hidden">Ачааллаж байна...</span>
                    </div>
                    <p class="mt-2 text-muted">Бэлгийн захиалгуудын мэдээлэл ачааллаж байна...</p>
                </div>

                <!-- Gift orders table -->
                <div *ngIf="!isLoading" class="table-responsive">
                    <table class="table table-bordered dt-responsive nowrap w-100">
                        <thead class="table-light">
                            <tr>
                                <th (click)="sortOrders('sender_name')" style="cursor: pointer;">
                                    Илгээгч
                                    <i [class]="getSortIcon('sender_name')"></i>
                                </th>
                                <th (click)="sortOrders('receiver_name')" style="cursor: pointer;">
                                    Хүлээн авагч
                                    <i [class]="getSortIcon('receiver_name')"></i>
                                </th>
                                <th>Металл төрөл</th>
                                <th (click)="sortOrders('quantity')" style="cursor: pointer;">
                                    Тоо хэмжээ
                                    <i [class]="getSortIcon('quantity')"></i>
                                </th>
                                <th>Мэндчилгээ</th>
                                <th (click)="sortOrders('status')" style="cursor: pointer;">
                                    Төлөв
                                    <i [class]="getSortIcon('status')"></i>
                                </th>
                                <th (click)="sortOrders('created_at')" style="cursor: pointer;">
                                    Үүсгэсэн огноо
                                    <i [class]="getSortIcon('created_at')"></i>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr *ngFor="let order of giftOrders; trackBy: trackByGiftOrder">
                                <td>
                                    <div>
                                        <h6 class="mb-1">{{ getSenderName(order) }}</h6>
                                        <small class="text-muted" *ngIf="order.sender?.phone">{{ order.sender.phone }}</small>
                                        <br *ngIf="order.sender?.phone && order.sender?.email">
                                        <small class="text-muted" *ngIf="order.sender?.email">{{ order.sender.email }}</small>
                                    </div>
                                </td>
                                <td>
                                    <div>
                                        <h6 class="mb-1">{{ getReceiverName(order) }}</h6>
                                        <small class="text-muted" *ngIf="order.receiver?.phone">{{ order.receiver.phone }}</small>
                                        <br *ngIf="order.receiver?.phone && order.receiver?.email">
                                        <small class="text-muted" *ngIf="order.receiver?.email">{{ order.receiver.email }}</small>
                                    </div>
                                </td>
                                <td>
                                    <span class="badge bg-warning" *ngIf="order.metal_id === 1">Алт</span>
                                    <span class="badge bg-light text-dark" *ngIf="order.metal_id === 3">Мөнгө</span>
                                    <span class="badge bg-secondary" *ngIf="order.metal_id !== 1 && order.metal_id !== 3">Тодорхойгүй</span>
                                </td>
                                <td>
                                    <strong>{{ order.quantity | number:'1.0-0' }} гр</strong>
                                </td>
                                <td>
                                    <div class="text-truncate" style="max-width: 200px;" [title]="order.greeting">
                                        {{ order.greeting || 'Мэндчилгээ байхгүй' }}
                                    </div>
                                </td>
                                <td>
                                    <span [class]="getStatusBadgeClass(order.status)">
                                        {{ getStatusText(order.status) }}
                                    </span>
                                </td>
                                <td>
                                    <small>{{ formatTimestamp(order.created_at) }}</small>
                                    <div *ngIf="order.cancelled_at" class="mt-1">
                                        <small class="text-danger">Цуцалсан: {{ formatTimestamp(order.cancelled_at) }}</small>
                                    </div>
                                    <div *ngIf="order.received_at" class="mt-1">
                                        <small class="text-success">Хүлээн авсан: {{ formatTimestamp(order.received_at) }}</small>
                                    </div>
                                </td>
                            </tr>
                            <tr *ngIf="giftOrders.length === 0">
                                <td colspan="8" class="text-center py-4">
                                    <div class="text-muted">
                                        <i class="mdi mdi-information-outline me-1"></i>
                                        <span *ngIf="!searchTerm && !statusFilter && !metalFilter && !dateFilter">
                                            Бэлгийн захиалга байхгүй байна.
                                        </span>
                                        <span *ngIf="searchTerm || statusFilter || metalFilter || dateFilter">
                                            Шүүлтийн нөхцөлд тохирох бэлгийн захиалга олдсонгүй.
                                        </span>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <!-- Pagination -->
                <div *ngIf="!isLoading && filteredGiftOrders.length > 0" class="row">
                    <div class="col-sm-12 col-md-5">
                        <div class="dataTables_info">
                            {{ startItem }}-ээс {{ endItem }} хүртэл, нийт {{ totalItems }}
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-7">
                        <div class="dataTables_paginate">
                            <nav aria-label="pagination">
                                <ul class="pagination justify-content-end">
                                    <li class="page-item" [class.disabled]="currentPage === 1">
                                        <button class="page-link" (click)="previousPage()"
                                            [disabled]="currentPage === 1">
                                            <i class="mdi mdi-chevron-left"></i>
                                        </button>
                                    </li>
                                    <li *ngFor="let page of getPageNumbers()" class="page-item"
                                        [class.active]="page === currentPage">
                                        <button class="page-link" (click)="goToPage(page)">
                                            {{ page }}
                                        </button>
                                    </li>
                                    <li class="page-item" [class.disabled]="currentPage === totalPages">
                                        <button class="page-link" (click)="nextPage()"
                                            [disabled]="currentPage === totalPages">
                                            <i class="mdi mdi-chevron-right"></i>
                                        </button>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// nextjs-admin/src/app/(dashboard)/gift_orders/page.tsx
"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  ChevronLeft,
  ChevronRight,
  FileSpreadsheet,
  Gift,
  Inbox,
  Loader2,
  RefreshCw,
  X,
} from "lucide-react";
import { toast } from "sonner";
import * as XLSX from "xlsx";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { useAuth } from "@/lib/auth/AuthProvider";
import {
  fetchGiftOrders,
  type GiftOrder,
  type GiftStatus,
} from "@/lib/firestore/giftOrders";
import {
  getReceiverName,
  getSenderName,
  giftStatusBadge,
  giftStatusText,
} from "@/lib/giftOrders";
import { formatOrderDate, formatQuantity, metalLabel } from "@/lib/orders";

type MetalFilter = "gold" | "silver" | "";
type SortField =
  | "sender_name"
  | "receiver_name"
  | "quantity"
  | "status"
  | "created_at";
type SortDir = "asc" | "desc";

const ITEMS_PER_PAGE = 20;

export default function GiftOrdersPage() {
  const { adminData } = useAuth();
  const canExportExcel = adminData?.role !== "manager";

  const [allOrders, setAllOrders] = useState<GiftOrder[]>([]);
  const [loading, setLoading] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");
  const [status, setStatus] = useState<GiftStatus>("");
  const [metal, setMetal] = useState<MetalFilter>("");
  const [dateFilter, setDateFilter] = useState("");
  const [page, setPage] = useState(1);
  const [sortField, setSortField] = useState<SortField>("created_at");
  const [sortDir, setSortDir] = useState<SortDir>("desc");

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const data = await fetchGiftOrders();
      setAllOrders(data);
    } catch (err) {
      console.error("Error fetching gift orders:", err);
      toast.error("Бэлгийн захиалгуудын мэдээлэл татахад алдаа гарлаа.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  const filtered = useMemo(() => {
    const term = searchTerm.trim().toLowerCase();
    let list = allOrders;

    if (term) {
      list = list.filter((o) => {
        const s = o.sender;
        const r = o.receiver;
        return (
          s?.first_name?.toLowerCase().includes(term) ||
          s?.last_name?.toLowerCase().includes(term) ||
          r?.first_name?.toLowerCase().includes(term) ||
          r?.last_name?.toLowerCase().includes(term) ||
          s?.phone?.includes(term) ||
          r?.phone?.includes(term) ||
          o.id?.toLowerCase().includes(term) ||
          o.greeting?.toLowerCase().includes(term)
        );
      });
    }
    if (status) {
      list = list.filter((o) => o.status === status);
    }
    if (metal) {
      const metalId = metal === "gold" ? 1 : 3;
      list = list.filter((o) => o.metal_id === metalId);
    }
    if (dateFilter) {
      const target = new Date(dateFilter).toDateString();
      list = list.filter(
        (o) => o.created_at?.toDate?.()?.toDateString() === target
      );
    }

    const dir = sortDir === "asc" ? 1 : -1;
    list = [...list].sort((a, b) => {
      const va = giftSortValue(a, sortField);
      const vb = giftSortValue(b, sortField);
      if (typeof va === "string" && typeof vb === "string") {
        return va.toLowerCase().localeCompare(vb.toLowerCase(), "mn") * dir;
      }
      if (va instanceof Date && vb instanceof Date) {
        return (va.getTime() - vb.getTime()) * dir;
      }
      return ((va as number) - (vb as number)) * dir;
    });
    return list;
  }, [allOrders, searchTerm, status, metal, dateFilter, sortField, sortDir]);

  const totalItems = filtered.length;
  const totalPages = Math.max(1, Math.ceil(totalItems / ITEMS_PER_PAGE));
  const currentPage = Math.min(page, totalPages);
  const startIndex = (currentPage - 1) * ITEMS_PER_PAGE;
  const endIndex = Math.min(startIndex + ITEMS_PER_PAGE, totalItems);
  const pageRows = filtered.slice(startIndex, endIndex);

  const handleSort = (field: SortField) => {
    if (sortField === field) {
      setSortDir((d) => (d === "asc" ? "desc" : "asc"));
    } else {
      setSortField(field);
      setSortDir(field === "created_at" ? "desc" : "asc");
    }
    setPage(1);
  };
  const handleSearch = (v: string) => { setSearchTerm(v); setPage(1); };
  const handleStatus = (v: GiftStatus) => { setStatus(v); setPage(1); };
  const handleMetal = (v: MetalFilter) => { setMetal(v); setPage(1); };
  const handleDate = (v: string) => { setDateFilter(v); setPage(1); };
  const handleRefresh = () => { setPage(1); void load(); };

  const hasAnyFilter = !!searchTerm || !!status || !!metal || !!dateFilter;

  const handleExport = () => {
    if (filtered.length === 0) {
      toast.warning("Экспорт хийх бэлгийн захиалга байхгүй байна.");
      return;
    }
    try {
      const rows = filtered.map((o) => ({
        "Бэлгийн захиалгын ID": o.id,
        "Илгээгч нэр": getSenderName(o),
        "Илгээгч утас": o.sender?.phone || "Байхгүй",
        "Илгээгч и-мэйл": o.sender?.email || "Байхгүй",
        "Хүлээн авагч нэр": getReceiverName(o),
        "Хүлээн авагч утас": o.receiver?.phone || "Байхгүй",
        "Хүлээн авагч и-мэйл": o.receiver?.email || "Байхгүй",
        "Металл төрөл": metalLabel(o.metal_id),
        "Тоо хэмжээ": o.quantity ?? 0,
        Мэндчилгээ: o.greeting || "Байхгүй",
        "Төлөв": giftStatusText(o.status),
        "Үүсгэсэн огноо": formatOrderDate(o.created_at),
        "Шинэчилсэн огноо": formatOrderDate(o.updated_at),
        "Цуцалсан огноо": formatOrderDate(o.cancelled_at),
        "Хүлээн авсан огноо": formatOrderDate(o.received_at),
      }));
      const ws = XLSX.utils.json_to_sheet(rows);
      ws["!cols"] = [
        { wch: 25 }, { wch: 20 }, { wch: 15 }, { wch: 25 },
        { wch: 20 }, { wch: 15 }, { wch: 25 }, { wch: 12 },
        { wch: 12 }, { wch: 30 }, { wch: 15 }, { wch: 20 },
        { wch: 20 }, { wch: 20 }, { wch: 20 },
      ];
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, "Бэлгийн захиалгууд");
      const today = new Date().toISOString().split("T")[0];
      const filename = `Бэлгийн_захиалгуудын_жагсаалт_${today}.xlsx`;
      XLSX.writeFile(wb, filename);
      toast.success(`${rows.length} захиалга экспортлогдлоо.`, {
        description: filename,
      });
    } catch (err) {
      console.error("Excel export error:", err);
      toast.error("Excel файл үүсгэхэд алдаа гарлаа.");
    }
  };

  const pages = useMemo(() => {
    const max = 5;
    const start = Math.max(1, currentPage - Math.floor(max / 2));
    const end = Math.min(totalPages, start + max - 1);
    return Array.from({ length: end - start + 1 }, (_, i) => start + i);
  }, [currentPage, totalPages]);

  return (
    <div className="space-y-5">
      <header className="space-y-1">
        <h1 className="text-[18px] font-semibold text-foreground">
          Бэлгийн захиалгууд
        </h1>
        <p className="text-[12px] text-muted-foreground">
          Бэлгийн захиалгууд <span className="text-foreground/70">/ Жагсаалт</span>
        </p>
      </header>

      <div className="rounded-xl border border-border-light bg-card">
        {/* Action bar */}
        <div className="flex flex-col gap-3 border-b border-border-light px-4 py-3 sm:flex-row sm:items-center sm:justify-between">
          <h2 className="text-[14px] font-semibold text-foreground">
            Бэлгийн захиалгын жагсаалт
          </h2>
          <div className="flex items-center gap-2">
            {canExportExcel && (
              <Button
                size="sm"
                onClick={handleExport}
                className="bg-[#1D6F42] text-white hover:bg-[#185c37]"
              >
                <FileSpreadsheet className="h-3.5 w-3.5" />
                Excel Export
              </Button>
            )}
            <Button
              variant="outline"
              size="icon-sm"
              onClick={handleRefresh}
              aria-label="Шинэчлэх"
            >
              <RefreshCw className={cn("h-3.5 w-3.5", loading && "animate-spin")} />
            </Button>
          </div>
        </div>

        {/* Filters */}
        <div className="grid gap-3 border-b border-border-light px-4 py-3 sm:grid-cols-2 lg:grid-cols-12">
          <div className="lg:col-span-5">
            <FieldLabel>Хайх</FieldLabel>
            <Input
              type="search"
              placeholder="Илгээгч/хүлээн авагчийн нэр, утас, мэндчилгээ…"
              value={searchTerm}
              onChange={(e) => handleSearch(e.target.value)}
            />
          </div>
          <div className="lg:col-span-2">
            <FieldLabel>Төлөв</FieldLabel>
            <Select
              value={status}
              onChange={(e) => handleStatus(e.target.value as GiftStatus)}
            >
              <option value="">Бүгд</option>
              <option value="pending">Хүлээгдэж буй</option>
              <option value="received">Хүлээн авсан</option>
              <option value="cancelled">Цуцалсан</option>
            </Select>
          </div>
          <div className="lg:col-span-2">
            <FieldLabel>Металл</FieldLabel>
            <Select
              value={metal}
              onChange={(e) => handleMetal(e.target.value as MetalFilter)}
            >
              <option value="">Бүгд</option>
              <option value="gold">Алт</option>
              <option value="silver">Мөнгө</option>
            </Select>
          </div>
          <div className="lg:col-span-3">
            <FieldLabel>Огноо</FieldLabel>
            <div className="flex items-stretch gap-1">
              <Input
                type="date"
                value={dateFilter}
                onChange={(e) => handleDate(e.target.value)}
                className="flex-1"
              />
              <Button
                variant="outline"
                size="icon-sm"
                onClick={() => handleDate("")}
                disabled={!dateFilter}
                aria-label="Огноо цэвэрлэх"
              >
                <X className="h-3.5 w-3.5" />
              </Button>
            </div>
          </div>
        </div>

        {/* Info bar */}
        <div className="border-b border-border-light px-4 py-2 text-[12px] text-muted-foreground">
          Нийт: <span className="font-medium text-foreground">{totalItems}</span> бэлгийн захиалга
          {hasAnyFilter && <span className="ml-1">(шүүлтийн дүн)</span>}
        </div>

        {/* Body */}
        <div className="px-4 py-3">
          {loading ? (
            <div className="flex flex-col items-center justify-center gap-2 py-12">
              <Loader2 className="h-5 w-5 animate-spin text-primary-600" />
              <p className="text-[12px] text-muted-foreground">
                Бэлгийн захиалгуудын мэдээлэл ачааллаж байна…
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full min-w-[960px] text-[13px]">
                <thead>
                  <tr className="border-b border-border-light text-[11px] uppercase tracking-[0.08em] text-muted-foreground">
                    <SortableHeader
                      label="Илгээгч"
                      field="sender_name"
                      sortField={sortField}
                      sortDir={sortDir}
                      onSort={handleSort}
                    />
                    <SortableHeader
                      label="Хүлээн авагч"
                      field="receiver_name"
                      sortField={sortField}
                      sortDir={sortDir}
                      onSort={handleSort}
                    />
                    <th className="px-2 py-2 text-left font-medium">Металл</th>
                    <SortableHeader
                      label="Тоо хэмжээ"
                      field="quantity"
                      sortField={sortField}
                      sortDir={sortDir}
                      onSort={handleSort}
                      align="right"
                    />
                    <th className="px-2 py-2 text-left font-medium">Мэндчилгээ</th>
                    <SortableHeader
                      label="Төлөв"
                      field="status"
                      sortField={sortField}
                      sortDir={sortDir}
                      onSort={handleSort}
                    />
                    <SortableHeader
                      label="Огноо"
                      field="created_at"
                      sortField={sortField}
                      sortDir={sortDir}
                      onSort={handleSort}
                    />
                  </tr>
                </thead>
                <tbody>
                  {pageRows.length === 0 && (
                    <tr>
                      <td
                        colSpan={7}
                        className="py-12 text-center text-muted-foreground"
                      >
                        <Inbox className="mx-auto mb-2 h-6 w-6 opacity-60" />
                        {hasAnyFilter
                          ? "Шүүлтийн нөхцөлд тохирох бэлгийн захиалга олдсонгүй."
                          : "Бэлгийн захиалга байхгүй байна."}
                      </td>
                    </tr>
                  )}
                  {pageRows.map((o) => (
                    <tr
                      key={o.id}
                      className="border-b border-border-light/60 last:border-b-0 hover:bg-muted/40"
                    >
                      <td className="px-2 py-2 align-top">
                        <PartyCell name={getSenderName(o)} party={o.sender} />
                      </td>
                      <td className="px-2 py-2 align-top">
                        <PartyCell name={getReceiverName(o)} party={o.receiver} />
                      </td>
                      <td className="px-2 py-2 align-top">
                        <span
                          className={cn(
                            "inline-flex items-center rounded-md px-1.5 py-0.5 text-[11px] font-medium",
                            o.metal_id === 1
                              ? "bg-amber-100 text-amber-700 dark:bg-amber-500/15 dark:text-amber-300"
                              : o.metal_id === 3
                                ? "bg-slate-100 text-slate-700 dark:bg-slate-500/15 dark:text-slate-300"
                                : "bg-muted text-muted-foreground"
                          )}
                        >
                          {metalLabel(o.metal_id)}
                        </span>
                      </td>
                      <td className="px-2 py-2 text-right align-top font-semibold tabular-nums">
                        {formatQuantity(o.metal_id, o.quantity)}
                      </td>
                      <td className="px-2 py-2 align-top">
                        <div
                          className="line-clamp-2 max-w-[240px] text-[12px] text-foreground/80"
                          title={o.greeting || ""}
                        >
                          {o.greeting ? (
                            <span className="inline-flex items-start gap-1">
                              <Gift className="mt-0.5 h-3 w-3 shrink-0 text-primary-500" />
                              <span>{o.greeting}</span>
                            </span>
                          ) : (
                            <span className="text-muted-foreground">
                              Мэндчилгээ байхгүй
                            </span>
                          )}
                        </div>
                      </td>
                      <td className="px-2 py-2 align-top">
                        <span
                          className={cn(
                            "inline-flex items-center rounded-md px-1.5 py-0.5 text-[11px] font-medium",
                            giftStatusBadge(o.status)
                          )}
                        >
                          {giftStatusText(o.status)}
                        </span>
                      </td>
                      <td className="px-2 py-2 align-top text-[11px] tabular-nums">
                        <div className="text-muted-foreground">
                          {formatOrderDate(o.created_at)}
                        </div>
                        {o.cancelled_at && (
                          <div className="mt-0.5 text-rose-600 dark:text-rose-400">
                            Цуцалсан: {formatOrderDate(o.cancelled_at)}
                          </div>
                        )}
                        {o.received_at && (
                          <div className="mt-0.5 text-emerald-600 dark:text-emerald-400">
                            Хүлээн авсан: {formatOrderDate(o.received_at)}
                          </div>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {!loading && totalItems > 0 && (
            <div className="mt-3 flex flex-col gap-2 border-t border-border-light pt-3 text-[12px] sm:flex-row sm:items-center sm:justify-between">
              <div className="text-muted-foreground">
                {startIndex + 1}–{endIndex} / Нийт:{" "}
                <span className="text-foreground">{totalItems}</span>
              </div>
              <div className="flex items-center gap-1">
                <Button
                  variant="outline"
                  size="sm"
                  disabled={currentPage === 1}
                  onClick={() => setPage(currentPage - 1)}
                >
                  <ChevronLeft className="h-3.5 w-3.5" />
                </Button>
                {pages.map((p) => (
                  <Button
                    key={p}
                    variant={p === currentPage ? "default" : "outline"}
                    size="sm"
                    onClick={() => setPage(p)}
                    className="min-w-8"
                  >
                    {p}
                  </Button>
                ))}
                <Button
                  variant="outline"
                  size="sm"
                  disabled={currentPage === totalPages}
                  onClick={() => setPage(currentPage + 1)}
                >
                  <ChevronRight className="h-3.5 w-3.5" />
                </Button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function giftSortValue(o: GiftOrder, field: SortField): string | number | Date {
  switch (field) {
    case "sender_name":
      return getSenderName(o).toLowerCase();
    case "receiver_name":
      return getReceiverName(o).toLowerCase();
    case "quantity":
      return o.quantity ?? 0;
    case "status":
      return o.status ?? "";
    case "created_at":
      return o.created_at?.toDate?.() ?? new Date(0);
  }
}

function PartyCell({
  name,
  party,
}: {
  name: string;
  party: GiftOrder["sender"];
}) {
  return (
    <div className="min-w-0">
      <div className="truncate font-medium text-foreground">{name}</div>
      {party?.phone && (
        <div className="truncate text-[11px] text-muted-foreground">
          {party.phone}
        </div>
      )}
      {!party?.phone && party?.email && (
        <div className="truncate text-[11px] text-muted-foreground">
          {party.email}
        </div>
      )}
    </div>
  );
}

function FieldLabel({ children }: { children: React.ReactNode }) {
  return (
    <div className="mb-1 text-[10px] font-medium uppercase tracking-[0.1em] text-muted-foreground">
      {children}
    </div>
  );
}

type SortableHeaderProps = {
  label: string;
  field: SortField;
  sortField: SortField;
  sortDir: SortDir;
  onSort: (field: SortField) => void;
  align?: "left" | "right";
};

function SortableHeader({
  label,
  field,
  sortField,
  sortDir,
  onSort,
  align = "left",
}: SortableHeaderProps) {
  const active = sortField === field;
  const Icon = !active ? ArrowUpDown : sortDir === "asc" ? ArrowUp : ArrowDown;
  return (
    <th
      className={cn(
        "px-2 py-2 font-medium",
        align === "right" ? "text-right" : "text-left"
      )}
    >
      <button
        type="button"
        onClick={() => onSort(field)}
        className={cn(
          "inline-flex items-center gap-1 transition-colors hover:text-foreground",
          align === "right" && "ml-auto",
          active && "text-foreground"
        )}
      >
        <span>{label}</span>
        <Icon className="h-3 w-3" />
      </button>
    </th>
  );
}
